name: Deploy to Beget

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to Beget via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USER }}
          password: ${{ secrets.BEGET_PASS }}
          local-dir: ./
          server-dir: /
          method: ftp
          dangerous-clean-slate: true
